services:
  - type: web    name: ai-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fix_template.py && gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false      - key: FIREBASE_MEASUREMENT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: FIREBASE_CREDENTIALS_BASE64
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
    plan: free
    autoDeploy: false